[DEFAULT]

# Default values are commented out below.
# Uncomment and change to set config wide defaults.

# number of images to produce per prompt
#num_outputs = 1

# number of denoising passes, higher produces higher quality
#num_inference_steps = 50

# output directory for generated images
#output_dir = "./output/"

# directory to look for model repositories
#models_dir = "~/src/huggingface.co/"

# diffusion model to use for inference
#model = "runwayml/stable-diffusion-v1-5"

# how closely to link images to prompt, higher can reduce image quality
#guidance_scale = 7

# allow automatic downloading of models
#download_models = false

# seed to use for generator
#seed = 0

# width of generated images
#width = 512

# height of generated images
#height = 512

# number of repetitions for task
#repeat = 1

# set default trigger phrase for models
model_triggers."prompthero/openjourney" = "mdjrny-v4 style"
model_triggers."prompthero/funko-diffusion" = "funko style"


[astronaut-rides-horse]

# diffusion model to use for inference
model = "runwayml/stable-diffusion-v1-5"

# prompts to generate images from
prompts = ["a photo of an astronaut riding a horse on mars"]


[female-elf-portrait]

# diffusion model to use for inference
model = "prompthero/openjourney"

# seed to use for generator
seed = 46041

# number of repetitions for task
repeat = 2

# prompts to generate images from
prompts = ["portrait of female elf, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha, 8k"]


[morgan-freeman-funko]

# diffusion model to use for inference
model = "prompthero/funko-diffusion"

# seed to use for generator
seed = 31911

# number of images to produce per prompt
num_outputs = 2

# prompts to generate images from
prompts = ["Morgan Freeman"]
